name: Build Geode Mod (nya~)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (meow)
        uses: actions/checkout@v4

      - name: Install build deps (rawr)
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake clang g++ unzip wget

      - name: Install Android NDK r27d (important!!)
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
          unzip android-ndk-r27d-linux.zip
          mv android-ndk-r27d $HOME/android-ndk

      - name: Configure CMake (uwu)
        run: cmake -S . -B build -G Ninja \
          -DGEODE_SDK_PATH="${{ github.workspace }}/Geode-sdk-real" \
          -DANDROID_NDK="$HOME/android-ndk"

      - name: Build mod (nyaaaa)
        run: cmake --build build --config Release

      - name: Upload artifact (mlem)
        uses: actions/upload-artifact@v4
        with:
          name: DemonButton
          path: build/*.geode
