name: Build Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build clang zip unzip

    - name: Install Android NDK 26
      run: |
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo mkdir -p /usr/local/lib/android/sdk/ndk
        curl -L https://dl.google.com/android/repository/android-ndk-r26d-linux.zip -o ndk.zip
        unzip ndk.zip -d /usr/local/lib/android/sdk/ndk
        mv /usr/local/lib/android/sdk/ndk/android-ndk-r26d /usr/local/lib/android/sdk/ndk/26.0.10792818

    - name: Download Geode CLI (v3.6.0)
      run: |
        curl -L -o geode.zip https://github.com/geode-sdk/cli/releases/download/v3.6.0/geode-cli-v3.6.0-linux.zip
        unzip geode.zip -d geode
        chmod +x geode/geode

    - name: Clean build folder
      run: rm -rf build

    - name: Build mod (force Android + correct NDK)
      run: ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/26.0.10792818 ./geode/geode build --platform android

    - name: Upload built mod
      uses: actions/upload-artifact@v4
      with:
        name: mod
        path: build/*.geode
