name: Build Geode Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential gcc g++ make

    - name: Make Geode CLI executable
      run: |
        chmod +x tools/geode
        echo "PATH=$PWD/tools:$PATH" >> $GITHUB_ENV

    - name: Initialize Geode toolchain
      run: geode setup

    - name: Build mod
      run: |
        export GEODE_SDK_TOOLCHAIN=native
        geode build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: geode-builds
        path: build/*.geode
